<?php

namespace Antropomorf\Swish;

if (!defined('ABSPATH')) {
  exit;
}

/**
 * Class QrCodeGenerator
 *
 * Generates this site's Swish QR code via Swish's own (unauthenticated,
 * confirmed live) QR API rather than requiring an editor to upload one
 * generated by hand at swish.nu/marknadsmaterial/qr-generator — regenerates
 * only when the number/amount/message/editable flags actually change
 * (Repository::sanitize() is the only caller, and only it knows both the
 * before and after values of one save), and caches the result to uploads/
 * as a single fixed-filename .webp file rather than a media library
 * attachment — this is a derived cache of the settings above, not
 * something an editor manages directly.
 *
 * @package Antropomorf\Swish
 */
class QrCodeGenerator
{
  private const API_URL = 'https://mpc.getswish.net/qrg-swish/api/v1/prefilled';

  /**
   * Square size in px requested from the API. No cropping needed (unlike
   * the original hand-uploaded-image spec) — the API already returns a
   * clean, centered square QR.
   */
  private const SIZE = 500;

  private const UPLOAD_SUBDIR = 'amrf-swish';
  private const FILENAME = 'swish-qr.webp';

  /**
   * @param array<string, string> $before Settings as they were before this save.
   * @param array<string, string> $after  Settings as sanitize() just computed them
   *                                      (qr_url/qr_source_hash keys not set yet).
   * @return array{qr_url: string, qr_source_hash: string} Merge this into
   *         the option being saved.
   */
  public static function maybeRegenerate(array $before, array $after): array
  {
    $hash = self::hash($after);

    if ($after['number'] === '') {
      // Nothing to generate without a number — clear any stale QR rather
      // than leaving a code for a number that's no longer configured.
      return ['qr_url' => '', 'qr_source_hash' => $hash];
    }

    if ($hash === $before['qr_source_hash'] && $before['qr_url'] !== '') {
      return ['qr_url' => $before['qr_url'], 'qr_source_hash' => $hash];
    }

    $url = self::generate($after);

    if ($url === null) {
      add_settings_error(
        Repository::OPTION_NAME,
        'amrf_swish_qr_failed',
        __('The Swish QR code could not be regenerated — the previous one (if any) is still in use. Try saving again.', 'amrf-admin')
      );
      // Deliberately keep the OLD hash, not the new one: the settings did
      // change, the cached QR is now stale relative to them, and keeping
      // the old hash means the next save (even with identical values)
      // retries instead of silently treating this as "already up to date."
      return ['qr_url' => $before['qr_url'], 'qr_source_hash' => $before['qr_source_hash']];
    }

    return ['qr_url' => $url, 'qr_source_hash' => $hash];
  }

  /**
   * @param array<string, string> $settings
   * @return string|null The final, cache-busted image URL, or null on
   *                      any failure (network, non-200, image conversion).
   */
  private static function generate(array $settings): ?string
  {
    $body = [
      'format' => 'png',
      'size' => self::SIZE,
      // Deliberately non-editable: this is the site's own receiving
      // account, not something a scanned code should let the payer
      // redirect elsewhere.
      'payee' => ['value' => $settings['number'], 'editable' => false],
    ];

    if ($settings['amount'] !== '') {
      $body['amount'] = ['value' => (float) $settings['amount'], 'editable' => $settings['amount_editable'] === '1'];
    }

    if ($settings['message'] !== '') {
      $body['message'] = ['value' => $settings['message'], 'editable' => $settings['message_editable'] === '1'];
    }

    $response = wp_remote_post(self::API_URL, [
      'headers' => ['Content-Type' => 'application/json'],
      'body' => wp_json_encode($body),
      'timeout' => 15,
    ]);

    if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
      return null;
    }

    $png = wp_remote_retrieve_body($response);
    if ($png === '') {
      return null;
    }

    return self::saveAsWebp($png);
  }

  /**
   * @param string $png Raw PNG bytes from the API.
   * @return string|null Cache-busted URL of the saved .webp, or null on failure.
   */
  private static function saveAsWebp(string $png): ?string
  {
    $upload_dir = wp_upload_dir();
    if (!empty($upload_dir['error'])) {
      return null;
    }

    $dir = trailingslashit($upload_dir['basedir']) . self::UPLOAD_SUBDIR;
    wp_mkdir_p($dir);

    $tmp_file = wp_tempnam('amrf-swish-qr.png');
    if ($tmp_file === false || file_put_contents($tmp_file, $png) === false) {
      return null;
    }

    $editor = wp_get_image_editor($tmp_file);
    if (is_wp_error($editor)) {
      wp_delete_file($tmp_file);
      return null;
    }

    $destination = trailingslashit($dir) . self::FILENAME;
    $saved = $editor->save($destination, 'image/webp');
    wp_delete_file($tmp_file);

    if (is_wp_error($saved)) {
      return null;
    }

    $url = trailingslashit($upload_dir['baseurl']) . self::UPLOAD_SUBDIR . '/' . self::FILENAME;

    // Fixed filename, always overwritten — a plain URL would otherwise
    // keep serving a browser/CDN-cached copy from before this save.
    return add_query_arg('v', substr(md5($png), 0, 8), $url);
  }

  /**
   * @param array<string, string> $settings
   */
  private static function hash(array $settings): string
  {
    return md5(implode('|', [
      $settings['number'],
      $settings['amount'],
      $settings['amount_editable'],
      $settings['message'],
      $settings['message_editable'],
    ]));
  }
}
