name: Generate Plugin Badges

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract plugin data
        id: plugin_data
        run: |
          PLUGIN_VERSION=$(grep "Version:" amrf-admin.php | sed 's/.*Version:[ 	]*//')
          echo "plugin_version=$PLUGIN_VERSION" >> $GITHUB_OUTPUT

          REQUIRES_WP=$(grep "Requires at least:" readme.txt | sed 's/.*Requires at least:[ 	]*//')
          echo "requires_wp=$REQUIRES_WP" >> $GITHUB_OUTPUT

          TESTED_WP=$(grep "Tested up to:" readme.txt | sed 's/.*Tested up to:[ 	]*//')
          echo "tested_wp=$TESTED_WP" >> $GITHUB_OUTPUT

      - name: Generate SVG badges
        run: |
          SHIELDS_URL="https://img.shields.io/badge"
          curl -s "$SHIELDS_URL/Plugin_Version-${{ steps.plugin_data.outputs.plugin_version }}-blue.svg" > plugin_version.svg
          curl -s "$SHIELDS_URL/Requires_WP-${{ steps.plugin_data.outputs.requires_wp }}-orange.svg?logo=wordpress" > requires_wp.svg
          curl -s "$SHIELDS_URL/Tested_WP-${{ steps.plugin_data.outputs.tested_wp }}-green.svg?logo=wordpress" > tested_wp.svg

      - name: Update Gist with SVGs
        env:
          GIST_SECRET: ${{ secrets.GIST_SECRET }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          gh auth login --with-token <<< "$GIST_SECRET"
          gh gist edit "$GIST_ID" plugin_version.svg requires_wp.svg tested_wp.svg
